# Generated by Django 3.0.2 on 2020-01-14 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_post_updated_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated_date',
        ),
    ]
